# Generated by Django 5.2.4 on 2025-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Unnamed User', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(default='TEMP', max_length=50),
        ),
    ]
